### ISSUE TITLE
Putting secrets in derivation could lead to leaking them

### ISSUE THREAD

**Issue by icewind1991** [mirkolenz/flocken#30]
The suggested way of loading secrets (`getEnv`) will put them in the nix store which in term might be uploaded to a publicly readable cache.

By only putting placeholders in the generated script and loading the environment variables at runtime instead this can be avoided (and it removes the need for `--impure`)

This already "just works" with at least some type of secrets by just setting the secrets to a bash environment variable but I haven't tested the others:

```nix
mkDockerManifest {
  tags = ["latest"];
  registries = {
    "docker.io" = {
      enable = true;
      repo = "xxxx";
      username = "$DOCKERHUB_USERNAME";
      password = "$DOCKERHUB_TOKEN";
    };
  };
  version = "1.0.0";
  images = with self.packages; [x86_64-linux.docker aarch64-linux.docker];
};
```

It would be good to update the documentation with either the above method or adding a warning against uploading the docker manifest script to a cache.

**Comment by mirkolenz** [comment]
Thanks for the heads-up, I updated the README accordingly (https://github.com/mirkolenz/flocken/commit/f38e71f29acecbf59964033dff8dc6c754ec379f). It is still necessary to run the derivation using the `--impure` flag in most cases (for instance, the GitHub integration gets the repo name and so on from environment variables), but for providing passwords your suggested method works perfectly fine. Thank you very much!
